// Conteúdo bilíngue do portfólio. Edite aqui textos, projetos, skills e contatos.

export const CONTENT = {
  pt: {
    role: 'UI/UX Designer',
    nav: [
      { label: 'Sobre', href: '#sobre' },
      { label: 'Projetos', href: '#projetos' },
      { label: 'Habilidades', href: '#habilidades' },
      { label: 'Experiência', href: '#experiencia' },
      { label: 'Contato', href: '#contato' },
    ],
    avail: 'Disponível para projetos',
    cta: 'Vamos conversar',
    heroL1: 'Design pensado',
    heroL2: 'para pessoas.',
    heroL3: 'Resultado sentido',
    heroL4: 'por negócios.',
    heroSub: 'Sou Rafael Casemiro — designer de produto focado em criar interfaces claras, bonitas e que convertem. Formado em Análise e Desenvolvimento de Sistemas, uno sensibilidade visual e visão técnica.',
    heroCta1: 'Ver projetos',
    heroCta2: 'Vamos conversar',
    scroll: 'Role para explorar',
    chipDesign: 'Design & Protótipo',
    chipDev: 'Pesquisa & Interação',
    aboutKicker: 'Sobre',
    aboutTitle: 'Onde design encontra engenharia.',
    aboutP1: 'Trabalho na interseção entre estética e funcionalidade. Cada decisão de interface nasce de pesquisa, intenção e atenção aos detalhes — do primeiro rascunho ao handoff.',
    aboutP2: 'Minha formação em Análise e Desenvolvimento de Sistemas pela Fatec me dá fluência técnica: entendo o que é viável, converso de igual para igual com engenharia e prototipo ideias até em código.',
    pillars: [
      { n: '01', title: 'Pesquisa & Estratégia', desc: 'Entendo o problema, o usuário e o negócio antes de desenhar a primeira tela.' },
      { n: '02', title: 'UI & Interação', desc: 'Interfaces limpas, hierarquia clara e micro-interações que dão vida ao produto.' },
      { n: '03', title: 'Protótipo & Handoff', desc: 'Do Figma ao código: protótipos navegáveis e entrega impecável para o time.' },
    ],
    projectsKicker: 'Projetos',
    projectsTitle: 'Trabalhos selecionados',
    projectsNote: 'Produtos digitais que desenhei e desenvolvi de ponta a ponta. Clique para visitar.',
    projects: [
      { mark: '01', img: '/assets/proj-claramente.png', link: 'https://claramente-xi.vercel.app', title: 'Claramente', category: 'UI/UX · Produto Digital', year: '2026', desc: 'Companheiro emocional com IA que ajuda pessoas a registrar humor, conversar e refletir sobre seus sentimentos. Projetei a experiência completa e desenvolvi o frontend em React integrado à API da Anthropic.', tags: ['IA Conversacional', 'PWA', 'Saúde Mental'], grad: 'linear-gradient(135deg,#1a1407,#a8841f,#ecc23a)', caseLabel: 'Visitar projeto', imgHint: 'Ao vivo ↗' },
      { mark: '02', img: '/assets/proj-agronomo.png', link: 'https://meu-agronomo-production-47ef.up.railway.app/login', title: 'Meu Agrônomo', category: 'UI/UX · Sistema Web / SaaS', year: '2026', desc: 'Sistema de gestão para agrônomos que substitui anotações em papel por agendamento inteligente, relatórios em PDF e um painel de métricas. Projetado e construído por mim de ponta a ponta.', tags: ['Agronegócio', 'Gestão', 'Laravel'], grad: 'linear-gradient(135deg,#0a0d16,#7a5f12,#cda32b)', caseLabel: 'Visitar projeto', imgHint: 'Ao vivo ↗' },
    ],
    skillsKicker: 'Habilidades',
    skillsTitle: 'Foco em UI/UX, com fluência técnica para tirar ideias do papel.',
    coreFocus: 'Foco principal',
    skills: [
      { label: 'UI/UX Design', icon: '✦', desc: 'Onde passo a maior parte do tempo: do conceito à interface final, com sistemas escaláveis e protótipos navegáveis.', grad: 'linear-gradient(135deg,#c69a23,#ecc23a)', items: ['Figma', 'Framer', 'Prototipagem', 'Design System', 'Wireframing', 'Auto Layout', 'Variants', 'Design Tokens', 'Componentização', 'Handoff'] },
      { label: 'Pesquisa & UX', icon: '◇', grad: 'linear-gradient(135deg,#a8841f,#ecc23a)', items: ['Pesquisa com usuário', 'Testes de usabilidade', 'Fluxos & Jornadas', 'Arquitetura da Informação', 'Acessibilidade'] },
      { label: 'Visual & Interação', icon: '◈', grad: 'linear-gradient(135deg,#7a5f12,#cda32b)', items: ['Tipografia', 'Layout & Grid', 'Cor & Hierarquia', 'Micro-interações', 'Motion'] },
      { label: 'Tech & Handoff', icon: '⟨⟩', grad: 'linear-gradient(135deg,#5a4a12,#c69a23)', items: ['HTML', 'CSS', 'JavaScript', 'React', 'Git'] },
    ],
    marquee: ['Figma', 'Framer', 'UI Design', 'UX Research', 'Prototipagem', 'Design System', 'Wireframing', 'Micro-interações', 'Acessibilidade', 'Handoff'],
    expKicker: 'Experiência & Formação',
    expTitle: 'Uma trajetória entre o pixel e o código.',
    timeline: [
      { period: '2026 — Atual', title: 'Aprimoramento contínuo', place: 'Estudos & Prática', desc: 'Aprofundando em Arquitetura de Sistemas, Engenharia de Prompt, Figma, Framer e UI Skills.' },
      { period: '2026', title: 'Análise e Desenvolvimento de Sistemas', place: 'Fatec · Formação concluída', desc: 'Graduação que une lógica, engenharia de software e pensamento de produto — base da minha visão técnica.' },
    ],
    contactKicker: 'Contato',
    contactTitle: 'Vamos criar algo juntos.',
    contactSub: 'Tem um projeto em mente ou quer trocar uma ideia? Preencha o formulário ou use um dos canais ao lado.',
    formNameLabel: 'Nome', formNamePh: 'Seu nome',
    formEmailLabel: 'Email', formEmailPh: 'seu@email.com',
    formMsgLabel: 'Mensagem', formMsgPh: 'Conte sobre seu projeto ou ideia...',
    formSend: 'Enviar mensagem', formSending: 'Enviando...', formSent: 'Mensagem enviada! Em breve retorno.', formErr: 'Algo deu errado. Tente pelo email ao lado.',
    contacts: [
      { label: 'Email', value: 'rafaelcasemiro.uiux@gmail.com', href: 'mailto:rafaelcasemiro.uiux@gmail.com' },
      { label: 'LinkedIn', value: '/in/rafael-casemiro', href: 'https://www.linkedin.com/in/rafael-casemiro-a91303306' },
      { label: 'Behance', value: '/rafaelcasemiro3', href: 'https://www.behance.net/rafaelcasemiro3' },
      { label: 'Instagram', value: '@rafaelcasemiro_', href: 'https://www.instagram.com/rafaelcasemiro_' },
      { label: 'WhatsApp', value: '+55 14 99616-9791', href: 'https://wa.me/5514996169791' },
      { label: 'GitHub', value: '/rafaelcasemiro01', href: 'https://github.com/rafaelcasemiro01' },
    ],
    footerNote: 'Feito com intenção.',
  },
  en: {
    role: 'UI/UX Designer',
    nav: [
      { label: 'About', href: '#sobre' },
      { label: 'Work', href: '#projetos' },
      { label: 'Skills', href: '#habilidades' },
      { label: 'Experience', href: '#experiencia' },
      { label: 'Contact', href: '#contato' },
    ],
    avail: 'Available for work',
    cta: "Let's talk",
    heroL1: 'Design made',
    heroL2: 'for people.',
    heroL3: 'Results felt',
    heroL4: 'by business.',
    heroSub: "I'm Rafael Casemiro — a product designer crafting clear, beautiful interfaces that convert. With a degree in Systems Analysis & Development, I blend visual sensibility with technical thinking.",
    heroCta1: 'View work',
    heroCta2: "Let's talk",
    scroll: 'Scroll to explore',
    chipDesign: 'Design & Prototype',
    chipDev: 'Research & Interaction',
    aboutKicker: 'About',
    aboutTitle: 'Where design meets engineering.',
    aboutP1: 'I work at the intersection of aesthetics and function. Every interface decision comes from research, intent and attention to detail — from first sketch to handoff.',
    aboutP2: 'My degree in Systems Analysis & Development from Fatec gives me technical fluency: I know what is feasible, speak engineering as a peer, and prototype ideas — even in code.',
    pillars: [
      { n: '01', title: 'Research & Strategy', desc: 'I understand the problem, the user and the business before designing a single screen.' },
      { n: '02', title: 'UI & Interaction', desc: 'Clean interfaces, clear hierarchy and micro-interactions that bring products to life.' },
      { n: '03', title: 'Prototype & Handoff', desc: 'From Figma to code: navigable prototypes and flawless delivery to the team.' },
    ],
    projectsKicker: 'Work',
    projectsTitle: 'Selected projects',
    projectsNote: 'Digital products I designed and built end-to-end. Click to visit.',
    projects: [
      { mark: '01', img: '/assets/proj-claramente.png', link: 'https://claramente-xi.vercel.app', title: 'Claramente', category: 'UI/UX · Digital Product', year: '2026', desc: 'An AI emotional companion that helps people log their mood, talk and reflect on their feelings. I designed the full experience and built the React frontend integrated with the Anthropic API.', tags: ['Conversational AI', 'PWA', 'Mental Health'], grad: 'linear-gradient(135deg,#1a1407,#a8841f,#ecc23a)', caseLabel: 'Visit project', imgHint: 'Live ↗' },
      { mark: '02', img: '/assets/proj-agronomo.png', link: 'https://meu-agronomo-production-47ef.up.railway.app/login', title: 'Meu Agrônomo', category: 'UI/UX · Web App / SaaS', year: '2026', desc: 'A management system for agronomists that replaces paper notes with smart scheduling, PDF reports and a metrics dashboard. Designed and built by me end-to-end.', tags: ['Agribusiness', 'Management', 'Laravel'], grad: 'linear-gradient(135deg,#0a0d16,#7a5f12,#cda32b)', caseLabel: 'Visit project', imgHint: 'Live ↗' },
    ],
    skillsKicker: 'Skills',
    skillsTitle: 'UI/UX at the core, with technical fluency to ship ideas.',
    coreFocus: 'Core focus',
    skills: [
      { label: 'UI/UX Design', icon: '✦', desc: 'Where I spend most of my time: from concept to final interface, with scalable systems and navigable prototypes.', grad: 'linear-gradient(135deg,#c69a23,#ecc23a)', items: ['Figma', 'Framer', 'Prototyping', 'Design System', 'Wireframing', 'Auto Layout', 'Variants', 'Design Tokens', 'Components', 'Handoff'] },
      { label: 'Research & UX', icon: '◇', grad: 'linear-gradient(135deg,#a8841f,#ecc23a)', items: ['User research', 'Usability testing', 'Flows & Journeys', 'Information Architecture', 'Accessibility'] },
      { label: 'Visual & Interaction', icon: '◈', grad: 'linear-gradient(135deg,#7a5f12,#cda32b)', items: ['Typography', 'Layout & Grid', 'Color & Hierarchy', 'Micro-interactions', 'Motion'] },
      { label: 'Tech & Handoff', icon: '⟨⟩', grad: 'linear-gradient(135deg,#5a4a12,#c69a23)', items: ['HTML', 'CSS', 'JavaScript', 'React', 'Git'] },
    ],
    marquee: ['Figma', 'Framer', 'UI Design', 'UX Research', 'Prototyping', 'Design System', 'Wireframing', 'Micro-interactions', 'Accessibility', 'Handoff'],
    expKicker: 'Experience & Education',
    expTitle: 'A path between pixel and code.',
    timeline: [
      { period: '2026 — Present', title: 'Continuous improvement', place: 'Studies & Practice', desc: 'Deepening in Systems Architecture, Prompt Engineering, Figma, Framer and UI Skills.' },
      { period: '2026', title: 'Systems Analysis & Development', place: 'Fatec · Degree completed', desc: 'A degree blending logic, software engineering and product thinking — the root of my technical vision.' },
    ],
    contactKicker: 'Contact',
    contactTitle: "Let's create something together.",
    contactSub: 'Got a project in mind or just want to chat? Fill the form or use one of the channels on the side.',
    formNameLabel: 'Name', formNamePh: 'Your name',
    formEmailLabel: 'Email', formEmailPh: 'you@email.com',
    formMsgLabel: 'Message', formMsgPh: 'Tell me about your project or idea...',
    formSend: 'Send message', formSending: 'Sending...', formSent: 'Message sent! I will get back soon.', formErr: 'Something went wrong. Try the email on the side.',
    contacts: [
      { label: 'Email', value: 'rafaelcasemiro.uiux@gmail.com', href: 'mailto:rafaelcasemiro.uiux@gmail.com' },
      { label: 'LinkedIn', value: '/in/rafael-casemiro', href: 'https://www.linkedin.com/in/rafael-casemiro-a91303306' },
      { label: 'Behance', value: '/rafaelcasemiro3', href: 'https://www.behance.net/rafaelcasemiro3' },
      { label: 'Instagram', value: '@rafaelcasemiro_', href: 'https://www.instagram.com/rafaelcasemiro_' },
      { label: 'WhatsApp', value: '+55 14 99616-9791', href: 'https://wa.me/5514996169791' },
      { label: 'GitHub', value: '/rafaelcasemiro01', href: 'https://github.com/rafaelcasemiro01' },
    ],
    footerNote: 'Made with intent.',
  },
};

// ⬇️ Para receber as mensagens no seu email: crie um form grátis em https://formspree.io
//    e cole o endpoint aqui (ex: 'https://formspree.io/f/abcdwxyz').
//    Enquanto for null, o botão abre o app de email já preenchido (fallback).
export const FORMSPREE_ENDPOINT = 'https://formspree.io/f/mgobgrdn';
export const CONTACT_EMAIL = 'rafaelcasemiro.uiux@gmail.com';
