// Conteúdo bilíngue do portfólio. Edite aqui textos, projetos, skills e contatos.

export const CONTENT = {
  pt: {
    role: 'UI/UX Designer',
    nav: [
      { label: 'Sobre', href: '#sobre' },
      { label: 'Projetos', href: '#projetos' },
      { label: 'Habilidades', href: '#habilidades' },
      { label: 'Experiência', href: '#experiencia' },
      { label: 'Contato', href: '#contato' },
    ],
    avail: 'Em busca da primeira oportunidade · UI/UX & Front-end',
    cta: 'Vamos conversar',
    heroL1: 'Design pensado',
    heroL2: 'para pessoas.',
    heroL3: 'Resultado sentido',
    heroL4: 'por negócios.',
    heroSub: 'Sou Rafael Casemiro e estou dando os primeiros passos como UI/UX Designer e desenvolvedor front-end. Gosto de criar interfaces claras, bonitas e fáceis de usar, e procuro minha primeira oportunidade na área para aprender e contribuir de verdade com um time.',
    heroCta1: 'Ver projetos',
    heroCta2: 'Vamos conversar',
    scroll: 'Role para explorar',
    chipDesign: 'Design & Protótipo',
    chipDev: 'Pesquisa & Interação',
    aboutKicker: 'Sobre',
    aboutTitle: 'Onde o design encontra a engenharia.',
    aboutP1: 'Gosto de trabalhar no ponto de encontro entre beleza e função. Procuro tomar cada decisão de interface com pesquisa, propósito e cuidado com os detalhes, do primeiro rascunho até a entrega para o time.',
    aboutP2: 'Sou aluno do último termo de Análise e Desenvolvimento de Sistemas na Fatec Ourinhos, com formatura prevista para dezembro de 2026. Essa base me ajuda a entender o lado técnico: o que dá para construir, como conversar com quem desenvolve e como transformar ideias em protótipos, às vezes direto em código. Ainda estou no começo da jornada e com muita vontade de aprender. Meu objetivo é me tornar Designer Engineer e, por enquanto, busco minha primeira oportunidade como UI/UX Designer e desenvolvedor front-end.',
    pillars: [
      { n: '01', title: 'Pesquisa & Estratégia', desc: 'Busco entender o problema, quem vai usar e o objetivo do negócio antes de desenhar a primeira tela.' },
      { n: '02', title: 'UI & Interação', desc: 'Interfaces organizadas, com hierarquia clara e pequenos detalhes de interação que dão vida ao produto.' },
      { n: '03', title: 'Protótipo & Entrega', desc: 'Do Figma ao código: protótipos navegáveis e uma entrega clara e bem organizada para o time.' },
    ],
    projectsKicker: 'Projetos',
    projectsTitle: 'Trabalhos selecionados',
    projectsNote: 'Projetos pessoais que desenhei e desenvolvi do início ao fim para aprender na prática. Clique para visitar.',
    projects: [
      { mark: '01', img: '/assets/proj-claramente.png', link: 'https://claramente-xi.vercel.app', title: 'Claramente', category: 'UI/UX · Produto Digital', year: '2026', desc: 'Companheiro emocional com inteligência artificial que ajuda as pessoas a registrar o humor, conversar e refletir sobre o que sentem. Desenhei toda a experiência e desenvolvi o front-end em React, integrado à API da Anthropic.', tags: ['IA Conversacional', 'PWA', 'Saúde Mental'], grad: 'linear-gradient(135deg,#1a1407,#a8841f,#ecc23a)', caseLabel: 'Visitar projeto', imgHint: 'Ao vivo ↗' },
      { mark: '02', img: '/assets/proj-agronomo.png', link: 'https://meu-agronomo-production-47ef.up.railway.app/login', title: 'Meu Agrônomo', category: 'UI/UX · Sistema Web / SaaS', year: '2026', desc: 'Sistema de gestão para agrônomos que troca as anotações em papel por agendamento inteligente, relatórios em PDF e um painel de métricas. Desenhei e construí tudo, do início ao fim.', tags: ['Agronegócio', 'Gestão', 'Laravel'], grad: 'linear-gradient(135deg,#0a0d16,#7a5f12,#cda32b)', caseLabel: 'Visitar projeto', imgHint: 'Ao vivo ↗' },
    ],
    skillsKicker: 'Habilidades',
    skillsTitle: 'Foco em UI/UX, com base técnica para tirar as ideias do papel.',
    coreFocus: 'Foco principal',
    skills: [
      { label: 'UI/UX Design', icon: '✦', desc: 'É onde passo a maior parte do tempo: do conceito à interface final, com sistemas escaláveis e protótipos navegáveis.', grad: 'linear-gradient(135deg,#c69a23,#ecc23a)', items: ['Figma', 'Framer', 'Prototipagem', 'Design System', 'Wireframing', 'Auto Layout', 'Variants', 'Design Tokens', 'Componentização', 'Handoff'] },
      { label: 'Pesquisa & UX', icon: '◇', grad: 'linear-gradient(135deg,#a8841f,#ecc23a)', items: ['Pesquisa com usuário', 'Testes de usabilidade', 'Fluxos & Jornadas', 'Arquitetura da Informação', 'Acessibilidade'] },
      { label: 'Visual & Interação', icon: '◈', grad: 'linear-gradient(135deg,#7a5f12,#cda32b)', items: ['Tipografia', 'Layout & Grid', 'Cor & Hierarquia', 'Micro-interações', 'Motion'] },
      { label: 'Tech & Handoff', icon: '⟨⟩', grad: 'linear-gradient(135deg,#5a4a12,#c69a23)', items: ['HTML', 'CSS', 'JavaScript', 'React', 'Git'] },
    ],
    marquee: ['Figma', 'Framer', 'UI Design', 'UX Research', 'Prototipagem', 'Design System', 'Wireframing', 'Micro-interações', 'Acessibilidade', 'Handoff'],
    expKicker: 'Experiência & Formação',
    expTitle: 'Uma trajetória entre o pixel e o código.',
    timeline: [
      { period: 'Objetivo', title: 'Rumo a Designer Engineer', place: 'UI/UX + Front-end', desc: 'Em busca da primeira oportunidade como UI/UX Designer e desenvolvedor front-end, com muita vontade de aprender e de unir design e código no mesmo trabalho.' },
          { period: 'Desde 2026', title: 'Aprimoramento contínuo', place: 'Estudos & Prática', desc: 'Me aprofundando em Arquitetura de Sistemas, Engenharia de Prompt, Figma, Framer e habilidades de UI.' },
      { period: 'Conclusão em Dez. 2026', title: 'Análise e Desenvolvimento de Sistemas', place: 'Fatec Ourinhos · Último termo', desc: 'Estou no último termo, com formatura prevista para dezembro de 2026. O curso une lógica, engenharia de software e visão de produto, a base do meu olhar técnico.' },
    ],
    contactKicker: 'Contato',
    contactTitle: 'Vamos criar algo juntos.',
    contactSub: 'Está com uma vaga, um projeto ou só quer trocar uma ideia? Vou adorar conversar. É só preencher o formulário ou falar comigo por um dos canais ao lado.',
    formNameLabel: 'Nome', formNamePh: 'Seu nome',
    formEmailLabel: 'Email', formEmailPh: 'seu@email.com',
    formMsgLabel: 'Mensagem', formMsgPh: 'Conte sobre seu projeto ou ideia...',
    formSend: 'Enviar mensagem', formSending: 'Enviando...', formSent: 'Mensagem enviada! Em breve retorno.', formErr: 'Algo deu errado. Tente pelo email ao lado.',
    contacts: [
      { label: 'Email', value: 'rafaelcasemiro.uiux@gmail.com', href: 'mailto:rafaelcasemiro.uiux@gmail.com' },
      { label: 'LinkedIn', value: '/in/rafael-casemiro', href: 'https://www.linkedin.com/in/rafael-casemiro-a91303306' },
      { label: 'Behance', value: '/rafaelcasemiro3', href: 'https://www.behance.net/rafaelcasemiro3' },
      { label: 'Instagram', value: '@rafaelcasemiro_', href: 'https://www.instagram.com/rafaelcasemiro_' },
      { label: 'WhatsApp', value: '+55 14 99616-9791', href: 'https://wa.me/5514996169791' },
      { label: 'GitHub', value: '/rafaelcasemiro01', href: 'https://github.com/rafaelcasemiro01' },
    ],
    footerNote: 'Feito com intenção.',
  },
  en: {
    role: 'UI/UX Designer',
    nav: [
      { label: 'About', href: '#sobre' },
      { label: 'Work', href: '#projetos' },
      { label: 'Skills', href: '#habilidades' },
      { label: 'Experience', href: '#experiencia' },
      { label: 'Contact', href: '#contato' },
    ],
    avail: 'Looking for my first opportunity · UI/UX & Front-end',
    cta: "Let's talk",
    heroL1: 'Design made',
    heroL2: 'for people.',
    heroL3: 'Results felt',
    heroL4: 'by business.',
    heroSub: "I'm Rafael Casemiro, taking my first steps as a UI/UX Designer and front-end developer. I love creating clear, beautiful and easy-to-use interfaces, and I'm looking for my first opportunity in the field to learn and make a real contribution to a team.",
    heroCta1: 'View work',
    heroCta2: "Let's talk",
    scroll: 'Scroll to explore',
    chipDesign: 'Design & Prototype',
    chipDev: 'Research & Interaction',
    aboutKicker: 'About',
    aboutTitle: 'Where design meets engineering.',
    aboutP1: 'I like to work where beauty meets function. I try to make every interface decision with research, purpose and care for the details, from the first sketch to the handoff to the team.',
    aboutP2: 'I am in the final term of my Systems Analysis & Development degree at Fatec Ourinhos, graduating in December 2026. This foundation helps me understand the technical side: what can be built, how to talk with developers, and how to turn ideas into prototypes, sometimes straight in code. I am still at the start of my journey and eager to learn. My goal is to become a Designer Engineer and, for now, I am looking for my first opportunity as a UI/UX Designer and front-end developer.',
    pillars: [
      { n: '01', title: 'Research & Strategy', desc: 'I try to understand the problem, who will use it and the business goal before designing a single screen.' },
      { n: '02', title: 'UI & Interaction', desc: 'Organized interfaces, with clear hierarchy and small interaction details that bring products to life.' },
      { n: '03', title: 'Prototype & Delivery', desc: 'From Figma to code: navigable prototypes and a clear, well-organized delivery to the team.' },
    ],
    projectsKicker: 'Work',
    projectsTitle: 'Selected projects',
    projectsNote: 'Personal projects I designed and built from start to finish to learn by doing. Click to visit.',
    projects: [
      { mark: '01', img: '/assets/proj-claramente.png', link: 'https://claramente-xi.vercel.app', title: 'Claramente', category: 'UI/UX · Digital Product', year: '2026', desc: 'An AI emotional companion that helps people log their mood, talk and reflect on how they feel. I designed the whole experience and built the React front-end, integrated with the Anthropic API.', tags: ['Conversational AI', 'PWA', 'Mental Health'], grad: 'linear-gradient(135deg,#1a1407,#a8841f,#ecc23a)', caseLabel: 'Visit project', imgHint: 'Live ↗' },
      { mark: '02', img: '/assets/proj-agronomo.png', link: 'https://meu-agronomo-production-47ef.up.railway.app/login', title: 'Meu Agrônomo', category: 'UI/UX · Web App / SaaS', year: '2026', desc: 'A management system for agronomists that replaces paper notes with smart scheduling, PDF reports and a metrics dashboard. Designed and built entirely by me, from start to finish.', tags: ['Agribusiness', 'Management', 'Laravel'], grad: 'linear-gradient(135deg,#0a0d16,#7a5f12,#cda32b)', caseLabel: 'Visit project', imgHint: 'Live ↗' },
    ],
    skillsKicker: 'Skills',
    skillsTitle: 'UI/UX at the core, with technical fluency to ship ideas.',
    coreFocus: 'Core focus',
    skills: [
      { label: 'UI/UX Design', icon: '✦', desc: 'Where I spend most of my time: from concept to final interface, with scalable systems and navigable prototypes.', grad: 'linear-gradient(135deg,#c69a23,#ecc23a)', items: ['Figma', 'Framer', 'Prototyping', 'Design System', 'Wireframing', 'Auto Layout', 'Variants', 'Design Tokens', 'Components', 'Handoff'] },
      { label: 'Research & UX', icon: '◇', grad: 'linear-gradient(135deg,#a8841f,#ecc23a)', items: ['User research', 'Usability testing', 'Flows & Journeys', 'Information Architecture', 'Accessibility'] },
      { label: 'Visual & Interaction', icon: '◈', grad: 'linear-gradient(135deg,#7a5f12,#cda32b)', items: ['Typography', 'Layout & Grid', 'Color & Hierarchy', 'Micro-interactions', 'Motion'] },
      { label: 'Tech & Handoff', icon: '⟨⟩', grad: 'linear-gradient(135deg,#5a4a12,#c69a23)', items: ['HTML', 'CSS', 'JavaScript', 'React', 'Git'] },
    ],
    marquee: ['Figma', 'Framer', 'UI Design', 'UX Research', 'Prototyping', 'Design System', 'Wireframing', 'Micro-interactions', 'Accessibility', 'Handoff'],
    expKicker: 'Experience & Education',
    expTitle: 'A path between pixel and code.',
    timeline: [
      { period: 'Goal', title: 'Becoming a Designer Engineer', place: 'UI/UX + Front-end', desc: 'Looking for my first opportunity as a UI/UX Designer and front-end developer, eager to learn and to blend design and code in the same role.' },
          { period: 'Since 2026', title: 'Continuous improvement', place: 'Studies & Practice', desc: 'Deepening my skills in Systems Architecture, Prompt Engineering, Figma, Framer and UI.' },
      { period: 'Graduating Dec 2026', title: 'Systems Analysis & Development', place: 'Fatec Ourinhos · Final term', desc: 'I am in my final term, graduating in December 2026. The course blends logic, software engineering and product thinking, the root of my technical vision.' },
    ],
    contactKicker: 'Contact',
    contactTitle: "Let's create something together.",
    contactSub: 'Have an opening, a project or just want to chat? I would love to talk. Just fill out the form or reach me through one of the channels on the side.',
    formNameLabel: 'Name', formNamePh: 'Your name',
    formEmailLabel: 'Email', formEmailPh: 'you@email.com',
    formMsgLabel: 'Message', formMsgPh: 'Tell me about your project or idea...',
    formSend: 'Send message', formSending: 'Sending...', formSent: 'Message sent! I will get back soon.', formErr: 'Something went wrong. Try the email on the side.',
    contacts: [
      { label: 'Email', value: 'rafaelcasemiro.uiux@gmail.com', href: 'mailto:rafaelcasemiro.uiux@gmail.com' },
      { label: 'LinkedIn', value: '/in/rafael-casemiro', href: 'https://www.linkedin.com/in/rafael-casemiro-a91303306' },
      { label: 'Behance', value: '/rafaelcasemiro3', href: 'https://www.behance.net/rafaelcasemiro3' },
      { label: 'Instagram', value: '@rafaelcasemiro_', href: 'https://www.instagram.com/rafaelcasemiro_' },
      { label: 'WhatsApp', value: '+55 14 99616-9791', href: 'https://wa.me/5514996169791' },
      { label: 'GitHub', value: '/rafaelcasemiro01', href: 'https://github.com/rafaelcasemiro01' },
    ],
    footerNote: 'Made with intent.',
  },
};

// ⬇️ Para receber as mensagens no seu email: crie um form grátis em https://formspree.io
//    e cole o endpoint aqui (ex: 'https://formspree.io/f/abcdwxyz').
//    Enquanto for null, o botão abre o app de email já preenchido (fallback).
export const FORMSPREE_ENDPOINT = 'https://formspree.io/f/mgobgrdn';
export const CONTACT_EMAIL = 'rafaelcasemiro.uiux@gmail.com';
